import Head from 'next/head'
import Image from 'next/image'
import { Anybody, Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link';
import { Loader } from "@googlemaps/js-api-loader"
import { useEffect } from 'react'
import Layout from '../components/layout';
require('dotenv').config()

export default function Home() {

  const loader = new Loader({
    apiKey: process.env.MAPS_API_KEY!,
    version: "weekly"
  });
  
  useEffect(() => {
   
    loader.load().then((google) => {
      let map = new google.maps.Map(document.getElementById("map") as HTMLElement, {
        center: { lat: -34.397, lng: 150.644 },
        zoom: 8,
      });
    });

})


  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div id="map" className={styles.map}></div>
      </main>
    </Layout>
  )
}
