import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/utils.module.css'
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export default function Splash() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.headingXl + " flex-center"}>
        <div >
          <h1 className="title">
            <Link href="/">Go to your map!</Link>
          </h1>
        </div>
      </main>
    </>
  )
}
